-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS TMDB_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Database & Schemas
CREATE DATABASE IF NOT EXISTS TMDB_DB;
CREATE SCHEMA IF NOT EXISTS TMDB_DB.RAW;
CREATE SCHEMA IF NOT EXISTS TMDB_DB.TRANSFORMED;
CREATE SCHEMA IF NOT EXISTS TMDB_DB.ANALYTICS;

-- Role and user
CREATE ROLE IF NOT EXISTS DATAIKU_ROLE;
GRANT USAGE ON WAREHOUSE TMDB_WH TO ROLE DATAIKU_ROLE;
GRANT USAGE ON DATABASE TMDB_DB TO ROLE DATAIKU_ROLE;
GRANT ALL ON SCHEMA TMDB_DB.RAW TO ROLE DATAIKU_ROLE;
GRANT ALL ON SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT ALL ON SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TMDB_DB.RAW TO ROLE DATAIKU_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA TMDB_DB.RAW TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TMDB_DB.RAW TO ROLE ACCOUNTADMIN;

-- Service user for Dataiku
CREATE USER IF NOT EXISTS DATAIKU_USER
    PASSWORD = 'PLACEHOLDER_REPLACED_BY_CICD'
    DEFAULT_ROLE = DATAIKU_ROLE
    DEFAULT_WAREHOUSE = TMDB_WH;

GRANT ROLE DATAIKU_ROLE TO USER DATAIKU_USER;