USE ROLE SYSADMIN;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS TMDB_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Database & Schemas
CREATE DATABASE IF NOT EXISTS TMDB_DB;
CREATE SCHEMA IF NOT EXISTS TMDB_DB.RAW;
CREATE SCHEMA IF NOT EXISTS TMDB_DB.TRANSFORMED;
CREATE SCHEMA IF NOT EXISTS TMDB_DB.ANALYTICS;

USE ROLE ACCOUNTADMIN;

-- Role and user
CREATE ROLE IF NOT EXISTS DATAIKU_ROLE;
GRANT ROLE DATAIKU_ROLE TO USER DATAIKU_USER;

-- Warehouse and database access
GRANT USAGE ON WAREHOUSE TMDB_WH TO ROLE DATAIKU_ROLE;
GRANT USAGE ON DATABASE TMDB_DB TO ROLE DATAIKU_ROLE;
GRANT ALL ON SCHEMA TMDB_DB.RAW TO ROLE DATAIKU_ROLE;
GRANT ALL ON SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT ALL ON SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;

-- Future object grants
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TMDB_DB.RAW TO ROLE DATAIKU_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;

-- Service user for Dataiku (key-pair auth set by CI/CD)
CREATE USER IF NOT EXISTS DATAIKU_USER
    DEFAULT_ROLE = DATAIKU_ROLE
    DEFAULT_WAREHOUSE = TMDB_WH;
