-- Row Access Policy
CREATE OR REPLACE ROW ACCESS POLICY TMDB_DB.TRANSFORMED.ADULT_CONTENT_POLICY
AS (adult BOOLEAN) RETURNS BOOLEAN ->
    CASE
        WHEN adult = FALSE THEN TRUE
        WHEN adult = TRUE AND CURRENT_ROLE() IN ('ACCOUNTADMIN', 'ADULT_CONTENT_ROLE') THEN TRUE
        ELSE FALSE
    END;

-- Tag-based masking
CREATE TAG IF NOT EXISTS TMDB_DB.TRANSFORMED.SENSITIVE_FINANCIAL;

CREATE OR REPLACE MASKING POLICY TMDB_DB.TRANSFORMED.FINANCIAL_MASK
AS (val NUMBER) RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN val
        ELSE NULL
    END;

ALTER TAG TMDB_DB.TRANSFORMED.SENSITIVE_FINANCIAL
    SET MASKING POLICY TMDB_DB.TRANSFORMED.FINANCIAL_MASK;

USE ROLE SYSADMIN;

-- Apply policies to Dynamic Tables (SYSADMIN owns the objects)
ALTER DYNAMIC TABLE TMDB_DB.TRANSFORMED.DT_MOVIES_ENRICHED
    ADD ROW ACCESS POLICY TMDB_DB.TRANSFORMED.ADULT_CONTENT_POLICY ON (adult);

ALTER DYNAMIC TABLE TMDB_DB.TRANSFORMED.DT_MOVIES_ENRICHED
    MODIFY COLUMN budget SET TAG TMDB_DB.TRANSFORMED.SENSITIVE_FINANCIAL = 'financial';

ALTER DYNAMIC TABLE TMDB_DB.TRANSFORMED.DT_MOVIES_ENRICHED
    MODIFY COLUMN revenue SET TAG TMDB_DB.TRANSFORMED.SENSITIVE_FINANCIAL = 'financial';
