USE ROLE SYSADMIN;

CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.RAW.DMF_NULL_VOTE_AVERAGE(
    ARG_T TABLE(vote_average FLOAT)
  )
  RETURNS NUMBER
  AS
  $$
    SELECT COUNT_IF(vote_average IS NULL) FROM ARG_T
  $$;

CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.RAW.DMF_DUPLICATE_MOVIES(
    ARG_T TABLE(movie_id NUMBER)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) - COUNT(DISTINCT movie_id) FROM ARG_T
$$;

CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.RAW.DMF_INVALID_RATINGS(
    ARG_T TABLE(vote_average FLOAT)
)
RETURNS NUMBER
AS
$$
SELECT COUNT_IF(vote_average < 0 OR vote_average > 10) FROM ARG_T
$$;

ALTER TABLE TMDB_DB.RAW.RAW_MOVIES
ADD DATA METRIC FUNCTION TMDB_DB.RAW.DMF_NULL_VOTE_AVERAGE ON ("vote_average");

ALTER TABLE TMDB_DB.RAW.RAW_MOVIES
ADD DATA METRIC FUNCTION TMDB_DB.RAW.DMF_DUPLICATE_MOVIES ON ("movie_id");

ALTER TABLE TMDB_DB.RAW.RAW_MOVIES
ADD DATA METRIC FUNCTION TMDB_DB.RAW.DMF_INVALID_RATINGS ON ("vote_average");

-- DMFs for TRANSFORMED layer
CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.TRANSFORMED.DMF_NULL_ROI(
    ARG_T TABLE(roi_pct NUMBER)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(roi_pct IS NULL) FROM ARG_T
$$;

CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.TRANSFORMED.DMF_INVALID_RATING_CATEGORY(
    ARG_T TABLE(rating_category VARCHAR)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(rating_category NOT IN ('Excellent', 'Good', 'Average', 'Poor')) FROM ARG_T
$$;

ALTER DYNAMIC TABLE TMDB_DB.TRANSFORMED.DT_MOVIES_ENRICHED
ADD DATA METRIC FUNCTION TMDB_DB.TRANSFORMED.DMF_NULL_ROI ON (roi_pct);

ALTER DYNAMIC TABLE TMDB_DB.TRANSFORMED.DT_MOVIES_ENRICHED
ADD DATA METRIC FUNCTION TMDB_DB.TRANSFORMED.DMF_INVALID_RATING_CATEGORY ON (rating_category);

-- DMFs for ANALYTICS layer
CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.ANALYTICS.DMF_ZERO_REVENUE_GENRES(
    ARG_T TABLE(total_revenue NUMBER)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(total_revenue = 0) FROM ARG_T
$$;

CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.ANALYTICS.DMF_NEGATIVE_ROI_GENRES(
    ARG_T TABLE(avg_roi_pct NUMBER)
)
RETURNS NUMBER
AS
$$
    SELECT COUNT_IF(avg_roi_pct < 0) FROM ARG_T
$$;

ALTER DYNAMIC TABLE TMDB_DB.ANALYTICS.DT_GENRE_ANALYTICS
ADD DATA METRIC FUNCTION TMDB_DB.ANALYTICS.DMF_ZERO_REVENUE_GENRES ON (total_revenue);

ALTER DYNAMIC TABLE TMDB_DB.ANALYTICS.DT_GENRE_ANALYTICS
ADD DATA METRIC FUNCTION TMDB_DB.ANALYTICS.DMF_NEGATIVE_ROI_GENRES ON (avg_roi_pct);

-- DMF usage grants — RAW
GRANT USAGE ON FUNCTION TMDB_DB.RAW.DMF_NULL_VOTE_AVERAGE(TABLE(FLOAT)) TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUNCTION TMDB_DB.RAW.DMF_DUPLICATE_MOVIES(TABLE(NUMBER)) TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUNCTION TMDB_DB.RAW.DMF_INVALID_RATINGS(TABLE(FLOAT)) TO ROLE DATAIKU_ROLE;

-- DMF usage grants — TRANSFORMED
GRANT USAGE ON FUNCTION TMDB_DB.TRANSFORMED.DMF_NULL_ROI(TABLE(NUMBER)) TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUNCTION TMDB_DB.TRANSFORMED.DMF_INVALID_RATING_CATEGORY(TABLE(VARCHAR)) TO ROLE DATAIKU_ROLE;

-- DMF usage grants — ANALYTICS
GRANT USAGE ON FUNCTION TMDB_DB.ANALYTICS.DMF_ZERO_REVENUE_GENRES(TABLE(NUMBER)) TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUNCTION TMDB_DB.ANALYTICS.DMF_NEGATIVE_ROI_GENRES(TABLE(NUMBER)) TO ROLE DATAIKU_ROLE;

-- Transfer ownership to DATAIKU_ROLE after all DDL on RAW_MOVIES is complete
GRANT OWNERSHIP ON TABLE TMDB_DB.RAW.RAW_MOVIES TO ROLE DATAIKU_ROLE COPY CURRENT GRANTS;
GRANT SELECT ON TABLE TMDB_DB.RAW.RAW_MOVIES TO ROLE SYSADMIN;
