CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.RAW.DMF_NULL_VOTE_AVERAGE(
    ARG_T TABLE(vote_average FLOAT)
  )
  RETURNS NUMBER
  AS
  $$
    SELECT COUNT_IF(vote_average IS NULL) FROM ARG_T
  $$;

CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.RAW.DMF_DUPLICATE_MOVIES(
ARG_T TABLE(movie_id NUMBER)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) - COUNT(DISTINCT movie_id) FROM ARG_T
$$;

CREATE OR REPLACE DATA METRIC FUNCTION TMDB_DB.RAW.DMF_INVALID_RATINGS(
ARG_T TABLE(vote_average FLOAT)
)
RETURNS NUMBER
AS
$$
SELECT COUNT_IF(vote_average < 0 OR vote_average > 10) FROM ARG_T
$$;

ALTER TABLE TMDB_DB.RAW.RAW_MOVIES
ADD DATA METRIC FUNCTION TMDB_DB.RAW.DMF_NULL_VOTE_AVERAGE ON ("vote_average");

ALTER TABLE TMDB_DB.RAW.RAW_MOVIES
ADD DATA METRIC FUNCTION TMDB_DB.RAW.DMF_DUPLICATE_MOVIES ON ("movie_id");

ALTER TABLE TMDB_DB.RAW.RAW_MOVIES
ADD DATA METRIC FUNCTION TMDB_DB.RAW.DMF_INVALID_RATINGS ON ("vote_average");