-- Dynamic table grants for existing objects
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;
GRANT OPERATE ON ALL DYNAMIC TABLES IN SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT OPERATE ON ALL DYNAMIC TABLES IN SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;

-- Dynamic table grants for future objects
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.TRANSFORMED TO ROLE DATAIKU_ROLE;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA TMDB_DB.ANALYTICS TO ROLE DATAIKU_ROLE;

-- Future tables in RAW (ensures grants survive write_dataframe recreation)
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA TMDB_DB.RAW TO ROLE DATAIKU_ROLE;
GRANT OWNERSHIP ON TABLE TMDB_DB.RAW.RAW_MOVIES TO ROLE DATAIKU_ROLE COPY CURRENT GRANTS;

-- ACCOUNTADMIN needs SELECT on RAW for dynamic table creation
GRANT SELECT ON ALL TABLES IN SCHEMA TMDB_DB.RAW TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TMDB_DB.RAW TO ROLE ACCOUNTADMIN;

-- DMF usage grants — RAW
GRANT USAGE ON FUNCTION TMDB_DB.RAW.DMF_NULL_VOTE_AVERAGE(TABLE(FLOAT)) TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUNCTION TMDB_DB.RAW.DMF_DUPLICATE_MOVIES(TABLE(NUMBER)) TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUNCTION TMDB_DB.RAW.DMF_INVALID_RATINGS(TABLE(FLOAT)) TO ROLE DATAIKU_ROLE;

-- DMF usage grants — TRANSFORMED
GRANT USAGE ON FUNCTION TMDB_DB.TRANSFORMED.DMF_NULL_ROI(TABLE(NUMBER)) TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUNCTION TMDB_DB.TRANSFORMED.DMF_INVALID_RATING_CATEGORY(TABLE(VARCHAR)) TO ROLE DATAIKU_ROLE;

-- DMF usage grants — ANALYTICS
GRANT USAGE ON FUNCTION TMDB_DB.ANALYTICS.DMF_ZERO_REVENUE_GENRES(TABLE(NUMBER)) TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUNCTION TMDB_DB.ANALYTICS.DMF_NEGATIVE_ROI_GENRES(TABLE(NUMBER)) TO ROLE DATAIKU_ROLE;

-- DATAIKU_USER role assignment
GRANT ROLE DATAIKU_ROLE TO USER DATAIKU_USER;
