-- Stage for AI Studio Semantic Model YAML (directory table required by AI Studio)
CREATE STAGE IF NOT EXISTS TMDB_DB.ANALYTICS.SEMANTIC_MODELS_STAGE
    DIRECTORY = (ENABLE = TRUE);

GRANT READ ON STAGE TMDB_DB.ANALYTICS.SEMANTIC_MODELS_STAGE TO ROLE DATAIKU_ROLE;
