CREATE OR REPLACE SEMANTIC VIEW TMDB_DB.ANALYTICS.TMDB_SEMANTIC_VIEW
    TABLES (
        TMDB_DB.ANALYTICS.DT_GENRE_ANALYTICS UNIQUE (GENRES, RELEASE_YEAR) COMMENT='The table contains aggregated analytics records summarizing movie performance metrics by genre and release year. Each record captures financial and audience reception data, including revenue, budget, return on investment, ratings, and popularity, along with the top-performing movie for each grouping.',
        TMDB_DB.TRANSFORMED.DT_MOVIES_ENRICHED COMMENT='The table contains records of movies with enriched metadata and performance metrics. Each record represents a single movie and includes details about its creative attributes such as genre, cast, and director, as well as financial and audience reception data including budget, revenue, and voting statistics.'
    )
    FACTS (
        DT_GENRE_ANALYTICS.AVG_POPULARITY AS AVG_POPULARITY COMMENT='The average popularity score associated with a genre.',
        DT_GENRE_ANALYTICS.AVG_RATING AS AVG_RATING COMMENT='The average rating score for a given genre.',
        DT_GENRE_ANALYTICS.AVG_ROI_PCT AS AVG_ROI_PCT COMMENT='The average return on investment (ROI) percentage for a given genre.',
        DT_GENRE_ANALYTICS.TOTAL_BUDGET AS TOTAL_BUDGET COMMENT='The total budget allocated for movies within a given genre.',
        DT_GENRE_ANALYTICS.TOTAL_MOVIES AS TOTAL_MOVIES COMMENT='The total number of movies associated with a given genre.',
        DT_GENRE_ANALYTICS.TOTAL_REVENUE AS TOTAL_REVENUE COMMENT='The total revenue generated, measured in monetary units.',
        DT_MOVIES_ENRICHED.BUDGET AS BUDGET COMMENT='The production budget allocated for a movie.',
        DT_MOVIES_ENRICHED.POPULARITY AS POPULARITY COMMENT='The popularity score of a movie as measured by The Movie Database (TMDB).',
        DT_MOVIES_ENRICHED.REVENUE AS REVENUE COMMENT='The total revenue generated by a movie.',
        DT_MOVIES_ENRICHED.ROI_PCT AS ROI_PCT COMMENT='The return on investment (ROI) for a movie expressed as a percentage.',
        DT_MOVIES_ENRICHED.VOTE_AVERAGE AS VOTE_AVERAGE COMMENT='The average vote score received by a movie based on user ratings.'
    )
    DIMENSIONS (
        DT_GENRE_ANALYTICS.GENRES AS GENRES COMMENT='A comma-separated list of genres associated with a title.',
        DT_GENRE_ANALYTICS.RELEASE_YEAR AS RELEASE_YEAR COMMENT='The year in which a title was released.',
        DT_GENRE_ANALYTICS.TOP_MOVIE AS TOP_MOVIE COMMENT='The title of the top-ranked movie associated with a given genre.',
        DT_MOVIES_ENRICHED.ADULT AS ADULT COMMENT='Indicates whether a movie is classified as adult content.',
        DT_MOVIES_ENRICHED.DIRECTOR AS DIRECTOR COMMENT='The name of the director of the movie.',
        DT_MOVIES_ENRICHED.GENRES AS GENRES COMMENT='The genres associated with a movie, which may include multiple genres.',
        DT_MOVIES_ENRICHED.KEYWORDS AS KEYWORDS COMMENT='Keywords or thematic tags associated with a movie.',
        DT_MOVIES_ENRICHED.MOVIE_ID AS MOVIE_ID COMMENT='Unique identifier for a movie.',
        DT_MOVIES_ENRICHED.ORIGINAL_LANGUAGE AS ORIGINAL_LANGUAGE COMMENT='The original language of the movie represented as a language code.',
        DT_MOVIES_ENRICHED.OVERVIEW AS OVERVIEW COMMENT='A brief narrative description or synopsis of the movie.',
        DT_MOVIES_ENRICHED.RATING_CATEGORY AS RATING_CATEGORY COMMENT='The qualitative rating category assigned to a movie based on its rating score.',
        DT_MOVIES_ENRICHED.RELEASE_YEAR AS RELEASE_YEAR COMMENT='The year in which a movie was released.',
        DT_MOVIES_ENRICHED.RUNTIME AS RUNTIME COMMENT='The runtime of a movie measured in minutes.',
        DT_MOVIES_ENRICHED.TITLE AS TITLE COMMENT='The title of the movie.',
        DT_MOVIES_ENRICHED.TOP_CAST AS TOP_CAST COMMENT='The names of the top-billed cast members associated with a movie.',
        DT_MOVIES_ENRICHED.VOTE_COUNT AS VOTE_COUNT COMMENT='The total number of votes cast by users for a movie.',
        DT_MOVIES_ENRICHED.RELEASE_DATE AS RELEASE_DATE COMMENT='The date on which a movie was released.'
    )
    AI_VERIFIED_QUERIES (
        "0;1" AS (
            QUESTION 'What are the highest rated movies by genre?'
            VERIFIED_AT 1779883662
            VERIFIED_BY 'Semantic Model Generator'
            ONBOARDING_QUESTION false
            SQL 'SELECT GENRES, TITLE, VOTE_AVERAGE, RATING_CATEGORY FROM dt_movies_enriched ORDER BY VOTE_AVERAGE DESC'),
        "1;1" AS (
            QUESTION 'What are the revenue and ratings for each movie genre by year?'
            VERIFIED_AT 1779883662
            VERIFIED_BY 'Semantic Model Generator'
            ONBOARDING_QUESTION false
            SQL 'SELECT GENRES, RELEASE_YEAR, AVG_RATING, TOTAL_REVENUE FROM dt_genre_analytics ORDER BY RELEASE_YEAR DESC'),
        "2;1" AS (
            QUESTION 'Which movies and directors have the best return on investment?'
            VERIFIED_AT 1779883662
            VERIFIED_BY 'Semantic Model Generator'
            ONBOARDING_QUESTION false
            SQL 'SELECT TITLE, BUDGET, REVENUE, ROI_PCT, DIRECTOR FROM dt_movies_enriched WHERE NOT ROI_PCT IS NULL ORDER BY ROI_PCT DESC')
    );

GRANT SELECT ON SEMANTIC VIEW TMDB_DB.ANALYTICS.TMDB_SEMANTIC_VIEW TO ROLE DATAIKU_ROLE;
